import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../components/layout/header';
import Footer from "../components/layout/footer";
import CartDrawer from "../components/cart/cartDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

interface LayoutProps {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Eko FoodHub Connect",
  description: "Generated by create next app",
};

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1">
            {children}
            <CartDrawer />
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;





